version: '3.2'
services:
  frontend:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - registry
    networks:
      dev_net:
    volumes:
      - ../:/source:rw
      - ./start-develop.sh:/root/start-develop.sh:ro
    environment:
      - DOCKER_REGISTRY_HOST=registry
      - DOCKER_REGISTRY_PORT=5000
      - NODE_NO_HTTP2=1
  registry:
    image: registry:2.1.1
    ports:
      - 5000:5000
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    networks:
      dev_net:
        aliases:
          - path-to-your-registry-v2
  nginx:
    image: nginx:1.13.12-alpine
    ports:
      - 8080:80
    networks:
      dev_net:
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro

networks:
  dev_net:
