version: "3"
services:
  frontend:
    build: .
    ports:
      - "9000:9000"
    environment:
      - DOCKER_REGISTRY_HOST=registry
      - DOCKER_REGISTRY_PORT=5000
      - NODE_NO_HTTP2=1
    depends_on:
      - registry
    networks:
      dev_net:
    volumes:
      - ../:/source:rw
      - ./start-develop.sh:/root/start-develop.sh:ro

  registry:
    image: registry:2.7
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    networks:
      dev_net:
        aliases:
          - registry

networks:
  dev_net:
    driver: bridge
